ATTACH TABLE _ UUID 'de11cc59-8afa-407a-a09e-5bb7f18bd131'
(
    `hostname` LowCardinality(String) COMMENT 'Hostname of the server executing the query.',
    `event_date` Date COMMENT 'The date when the event happened.',
    `event_time` DateTime COMMENT 'The date and time when the event happened.',
    `event_time_microseconds` DateTime64(6) COMMENT 'The date and time with microseconds precision when the event happened.',
    `id` UInt64 COMMENT 'ID of processor.',
    `parent_ids` Array(UInt64) COMMENT 'Parent processors IDs.',
    `plan_step` UInt64 COMMENT 'ID of the query plan step which created this processor. The value is zero if the processor was not added from any step.',
    `plan_group` UInt64 COMMENT 'Group of the processor if it was created by query plan step. A group is a logical partitioning of processors added from the same query plan step. Group is used only for beautifying the result of EXPLAIN PIPELINE result.',
    `initial_query_id` String COMMENT 'ID of the initial query (for distributed query execution).',
    `query_id` String COMMENT 'ID of the query.',
    `name` LowCardinality(String) COMMENT 'Name of the processor.',
    `elapsed_us` UInt64 COMMENT 'Number of microseconds this processor was executed.',
    `input_wait_elapsed_us` UInt64 COMMENT 'Number of microseconds this processor was waiting for data (from other processor).',
    `output_wait_elapsed_us` UInt64 COMMENT 'Number of microseconds this processor was waiting because output port was full.',
    `input_rows` UInt64 COMMENT 'The number of rows consumed by processor.',
    `input_bytes` UInt64 COMMENT 'The number of bytes consumed by processor.',
    `output_rows` UInt64 COMMENT 'The number of rows generated by processor.',
    `output_bytes` UInt64 COMMENT 'The number of bytes generated by processor.'
)
ENGINE = MergeTree
PARTITION BY toYYYYMM(event_date)
ORDER BY (event_date, event_time)
SETTINGS index_granularity = 8192
COMMENT 'Contains profiling information on processors level (building blocks for a pipeline for query execution.'
