/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package ru.otus.kafka;
@org.apache.avro.specific.AvroGenerated
public enum Rating implements org.apache.avro.generic.GenericEnumSymbol<Rating> {
  EXCELLENT, GOOD, AVERAGE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Rating\",\"namespace\":\"ru.otus.kafka\",\"symbols\":[\"EXCELLENT\",\"GOOD\",\"AVERAGE\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
