{
 "title": "Kafka",
 "description": "Kafka resource usage and throughput",
 "tags": [ "Kafka" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(kafka_exporter_build_info, job)"
   },
   {
    "name": "node",
    "label": "Host",
    "query": "label_values(kafka_brokers{job=~\"$job\"}, instance)"
   },
   {
    "name": "port",
    "label": "Port",
    "query": "label_values(kafka_brokers{job=~\"$job\"}, instance)"
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": "label_values(kafka_topic_partition_current_offset{topic!='__consumer_offsets',topic!='--kafka'}, topic)"
   }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$node - Message in per second",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "repeat": "node",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_topic_partition_current_offset[1m])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "$node - Message in per minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "repeat": "node",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(kafka_topic_partition_current_offset[5m])/5) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "$node - Kafka broker",
   "type": "graph",
   "description": "Number of Brokers in the Kafka Cluster",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "repeat": "node",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kafka_brokers", "legendFormat": "Number of brokers" }
   ]
  },
  {
   "title": "$node - Oldest Offset of a Broker at Topic/Partition",
   "type": "graph",
   "description": "Oldest Offset of a Broker at Topic/Partition",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "repeat": "node",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_topic_partition_oldest_offset{topic!=\"__consumer_offsets\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "$node - Number of Replicas for this Topic/Partition",
   "type": "graph",
   "description": "Number of Replicas for this Topic/Partition",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
   "repeat": "node",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_topic_partition_replicas{topic!=\"__consumer_offsets\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "$node - Number of In-Sync Replicas for this Topic/Partition",
   "type": "graph",
   "description": "Number of In-Sync Replicas for this Topic/Partition",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 30 },
   "repeat": "node",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_topic_partition_in_sync_replica{topic!=\"__consumer_offsets\"}",
     "legendFormat": "Replicas-{{topic}}"
    }
   ]
  },
  {
   "title": "$node - Number Topic/Partition is under Replicated",
   "type": "graph",
   "description": "If Topic/Partition is under Replicated\n\n``0`` - No\n\n``1`` - Yes",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 36 },
   "repeat": "node",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_topic_partition_under_replicated_partition{topic!=\"__consumer_offsets\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": " if Topic/Partition is using the Preferred Broker",
   "type": "graph",
   "description": "If Topic/Partition is using the Preferred Broker\n\n``0`` - No\n\n``1`` - Yes",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 42 },
   "repeat": "node",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_topic_partition_leader_is_preferred{topic!=\"__consumer_offsets\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "$node - Leader Broker ID of this Topic/Partition",
   "type": "gauge",
   "description": "Leader Broker ID of this Topic/Partition",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 48 },
   "repeat": "node",
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kafka_topic_partition_leader{topic!=\"__consumer_offsets\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "$node - Partitions per Topic",
   "type": "barchart",
   "description": "Number of partitions for this Topic",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 54 },
   "repeat": "node",
   "targets": [
    {
     "expr": "sum by(topic) (kafka_topic_partitions{instance=\"$node:$port\",topic=~\"$topic\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  }
 ]
}