{
 "title": "Kafka JMX Exporter",
 "description": "Kafka resource usage and throughput",
 "tags": [ "Kafka" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": "label_values(jvm_info,job)" },
   {
    "name": "node",
    "label": "Host",
    "query": "label_values(jvm_info{job=~\"$job\"},instance)"
   },
   {
    "name": "port",
    "label": "Port",
    "query": "label_values(jvm_info{job=~\"$job\"},instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "$node - CPU Usage",
   "type": "graph",
   "description": "Total user and system CPU time spent in seconds",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "repeat": "node",
   "yaxes": [
    { "format": "short", "label": "Cores" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=\"$node:$port\",job='$job'}[1m])",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "$node - JVM Memory Used",
   "type": "graph",
   "description": "Used bytes of a given JVM memory area",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "repeat": "node",
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "sum without(area)(jvm_memory_bytes_used{instance=\"$node:$port\",job='$job'})",
     "legendFormat": "Memory  - Usage"
    },
    {
     "expr": "sum without(area)(jvm_memory_bytes_max{instance=\"$node:$port\",job='$job'})",
     "legendFormat": "Memory - Max available"
    }
   ]
  },
  {
   "title": "$node - Time spent in GC",
   "type": "graph",
   "description": "Time spent in a given JVM garbage collector in seconds",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "repeat": "node",
   "yaxes": [
    { "format": "percentunit", "label": "% time in GC" }
   ],
   "targets": [
    {
     "expr": "sum without(gc)(rate(jvm_gc_collection_seconds_sum{instance=\"$node:$port\",job='$job'}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "$node - Messages In Per Topic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 57 },
   "repeat": "node",
   "yaxes": [
    { "format": "short", "label": "Messages/s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(rate(kafka_server_brokertopicmetrics_messagesin_total{instance=\"$node:$port\",job='$job',topic!=\"\"}[5m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "$node - Bytes In Per Topic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 75 },
   "repeat": "node",
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(rate(kafka_server_brokertopicmetrics_bytesin_total{instance=\"$node:$port\",job='$job',topic!=\"\"}[5m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "$node - Bytes Out Per Topic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 93 },
   "repeat": "node",
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(rate(kafka_server_brokertopicmetrics_bytesout_total{instance=\"$node:$port\",job='$job',topic!=\"\"}[5m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "$node - Logs size",
   "type": "graph",
   "description": "Logs size",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 117 },
   "repeat": "node",
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "kafka_log_log_size {instance=\"$node:$port\",job='$job',topic!=\"\"} ",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "$node - Number of requests per second",
   "type": "graph",
   "description": "Number of requests per second",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 141 },
   "repeat": "node",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_network_requestmetrics_requests_total{instance=~'$node:$port',job='$job',request=\"FetchConsumer\"}[1m])",
     "legendFormat": "{{request}}"
    },
    {
     "expr": "rate(kafka_network_requestmetrics_requests_total{instance=~'$node:$port',job='$job',request=\"Fetch\"}[1m])",
     "legendFormat": "{{request}}"
    },
    {
     "expr": "rate(kafka_network_requestmetrics_requests_total{instance=~'$node:$port',job='$job',request=\"Produce\"}[1m])",
     "legendFormat": "{{request}}"
    }
   ]
  },
  {
   "title": "$node -  The average fraction of time the network processors are idle",
   "type": "graph",
   "description": "The average fraction of time the network processors are idle",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 159 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(kafka_network_socketserver_networkprocessoravgidlepercent{instance=~'$node:$port',job='$job'}) * 100",
     "legendFormat": "Idle time in %"
    }
   ]
  },
  {
   "title": "$node  - Time to process a request",
   "type": "graph",
   "description": "Time it takes to process a request. ",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 165 },
   "repeat": "node",
   "yaxes": [
    { "format": "short", "label": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_network_requestmetrics_totaltimems{instance=\"$node:$port\",job=\"jmx-kafka-exporter\",request=~\"Produce|FetchFollower|FetchConsumer\"}[1m])",
     "legendFormat": "{{request}}-quantile-{{quantile}}"
    }
   ]
  },
  {
   "title": "$node - Asynchronous disk log flush and time in ms",
   "type": "graph",
   "description": "Asynchronous disk log flush and time in ms",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 183 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_log_logflushstats_logflushrateandtimems{instance=\"$node:$port\",job='$job'}",
     "legendFormat": "log flush time - quantile {{quantile}}"
    }
   ]
  },
  {
   "title": "$node - Number of partitions on the system",
   "type": "graph",
   "description": "Number of partitions on  the system",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 189 },
   "repeat": "node",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_replicamanager_partitioncount{instance=~'$node:$port',job='$job'}",
     "legendFormat": "Number of partitions on  the system"
    }
   ]
  },
  {
   "title": "$node - Offline partitions count",
   "type": "graph",
   "description": "Number of partitions without an active leader, therefore not readable nor writeable",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 207 },
   "repeat": "node",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_offlinepartitionscount{instance=~'$node:$port',job='$job'}",
     "legendFormat": "Offline Partitions Count"
    }
   ]
  },
  {
   "title": "$node - Number of disputed leader elections rate",
   "type": "graph",
   "description": "Number of disputed leader elections rate",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 225 },
   "repeat": "node",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_controller_controllerstats_leaderelectionrateandtimems{instance=~'$node:$port',job='$job',quantile=\"0.999\"}",
     "legendFormat": "Number of disputed leader elections rate"
    }
   ]
  },
  {
   "title": "$node - Active controller count",
   "type": "graph",
   "description": "Number of active controller brokers",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 243 },
   "repeat": "node",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_activecontrollercount{instance=~'$node:$port',job='$job'}",
     "legendFormat": "Active controller count"
    }
   ]
  },
  {
   "title": "$node -  Count IsrShrinks/IsrExpands",
   "type": "graph",
   "description": "When a broker goes down, ISR will shrink for some of the partitions. When that broker is up again, ISR will be expanded once the replicas have fully caught up.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 261 },
   "repeat": "node",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_replicamanager_isrshrinks_total{instance=~'$node:$port',job='$job'}[1m])",
     "legendFormat": "IsrShrinksPerSec"
    },
    {
     "expr": "rate(kafka_server_replicamanager_isrexpands_total{instance=~'$node:$port',job='$job'}[1m])",
     "legendFormat": "IsrExpandsPerSec"
    }
   ]
  }
 ]
}